services:
  jaeger:
    image: jaegertracing/all-in-one:1.76.0
    container_name: jaeger
    restart: unless-stopped
    user: root
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - SPAN_STORAGE_TYPE=badger
      - BADGER_EPHEMERAL=false
      - BADGER_DIRECTORY_VALUE=/badger/data
      - BADGER_DIRECTORY_KEY=/badger/key
      - BADGER_SPAN_STORE_TTL=72h
      - BADGER_VALUE_LOG_GC_TRIGGER=0.8
    ports:
      - "16686:16686"
      - "4317:4317"
    volumes:
      - jaeger_data:/badger

volumes:
  jaeger_data: