// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: archive/archive.proto

package api

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on DummyRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *DummyRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DummyRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in DummyRequestMultiError, or
// nil if none found.
func (m *DummyRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *DummyRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return DummyRequestMultiError(errors)
	}

	return nil
}

// DummyRequestMultiError is an error wrapping multiple validation errors
// returned by DummyRequest.ValidateAll() if the designated constraints aren't met.
type DummyRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DummyRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DummyRequestMultiError) AllErrors() []error { return m }

// DummyRequestValidationError is the validation error returned by
// DummyRequest.Validate if the designated constraints aren't met.
type DummyRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DummyRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DummyRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DummyRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DummyRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DummyRequestValidationError) ErrorName() string { return "DummyRequestValidationError" }

// Error satisfies the builtin error interface
func (e DummyRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDummyRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DummyRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DummyRequestValidationError{}

// Validate checks the field values on DummyResponse with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *DummyResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DummyResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in DummyResponseMultiError, or
// nil if none found.
func (m *DummyResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *DummyResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Code

	if len(errors) > 0 {
		return DummyResponseMultiError(errors)
	}

	return nil
}

// DummyResponseMultiError is an error wrapping multiple validation errors
// returned by DummyResponse.ValidateAll() if the designated constraints
// aren't met.
type DummyResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DummyResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DummyResponseMultiError) AllErrors() []error { return m }

// DummyResponseValidationError is the validation error returned by
// DummyResponse.Validate if the designated constraints aren't met.
type DummyResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DummyResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DummyResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DummyResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DummyResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DummyResponseValidationError) ErrorName() string { return "DummyResponseValidationError" }

// Error satisfies the builtin error interface
func (e DummyResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDummyResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DummyResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DummyResponseValidationError{}
